name: CI Test

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  lint-front-end:
    name: Run ESLint on client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: 14.*

      - name: Install node dependencies
        run: cd client && npm install

      - name: Run ESLint
        run: cd client && npm run lint

  front-end:
    name: Build react client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: 14.*

      - name: Install node dependencies
        run: cd client && npm install

      - name: Run build script
        run: cd client && npm run-script build
        env:
          CI: ""

  back-end:
    name: Start node server on production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.*

      - name: Install node dependencies
        run: cd server && npm install

      - name: Start node server
        run: cd server && npm run start-ci
        env:
          MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ENV: PROD
          CI: true
          PORT: 9001

