name: Continuous Integration Test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  front-end:
    name: Build react client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install node dependencies
        run: cd client && npm install

      - name: Run build script
        run: cd client && npm run-script build --watchAll=false --ci=false

  back-end:
    name: Start node server on production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Set private keys for production environment
        uses: SpicyPizza/create-envfile@v1.0
        with:
          envkey_MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}
          envkey_ENV: PROD
          envkey_CI: true
          envkey_PORT: 9001
          directory: server
          file_name: .env

      - name: Install node dependencies
        run: cd server && npm install

      - name: Start node server
        run: cd server && npm run start-ci
